export const mytools = [
  {
    "logo": "/assets/img/logos/sgame.svg",
    "route": "https://sgame.etsisi.upm.es/",
    "title": "SGAME",
    "translationKey": "tools.toolCards.description.1",
    "github": "https://github.com/CyberAula/sgame_platform",
    "gradient": "bg-blue-gradient-plain ",
    "key":"1",
  },
  {
    "logo": "/assets/img/logos/escapp.svg",
    "route": "https://escape.dit.upm.es/",
    "title": "Educational Escape Rooms", 
    "translationKey": "tools.toolCards.description.2",
    "github": "https://github.com/ging/escapp",
    "gradient": "bg-purple-gradient-plain",
    "key":"2",
  },
  {
    "logo": "/assets/img/logos/school.svg",
    "route": "https://cyberaula.github.io/quiz-converter/",
    "title": "QUIZ converter",
    "translationKey": "tools.toolCards.description.3",
    "github": "https://github.com/CyberAula/quiz-converter",
    "gradient": "bg-yellow-gradient-plain",
    "key":"3",
  
  },
  {
    "logo": "/assets/img/logos/school.svg",
    "route": "https://sonsoles.me/RESCORM-quiz-generator/",
    "title": "RESCORM Quiz generator",
    "translationKey": "tools.toolCards.description.4",  
    "github": "https://github.com/sonsoleslp/RESCORM-quiz-generator",
    "gradient": "bg-purple-gradient-plain",
    "key":"4",
  },
  {
    "logo": "/assets/img/logos/codeditor.png",
    "route": "https://github.com/agordillo/CODEditor",
    "title": "CODEditor",
    "translationKey": "tools.toolCards.description.3",
    "github": "https://github.com/agordillo/CODEditor",
    "gradient": "bg-blue-gradient-plain",
    "key":"5",
  },
  {
    "logo": "/assets/img/logos/loep.svg",
    "route": "https://github.com/agordillo/LOEP",
    "title": "LOEP",
    "translationKey": "tools.toolCards.description.3",
    "github": "https://github.com/agordillo/LOEP",
    "gradient": "bg-yellow-gradient-plain",
    "key":"6",
  },
  {
    "logo": "/assets/img/logos/europeana.png",
    "route": "https://github.com/agordillo/EuropeanaRS",
    "title": "EuropeanaRS",
    "translationKey": "tools.toolCards.description.3",
    "github": "https://github.com/agordillo/EuropeanaRS",
    "gradient": "bg-purple-gradient-plain",
    "key":"7",
  },
 
  {
    "logo": "/assets/img/logos/rescorm.svg",
    "route": "https://github.com/agordillo/RESCORM",
    "title": "RESCORM",
    "translationKey": "tools.toolCards.description.3",
    "github": "https://github.com/agordillo/RESCORM",
    "gradient": "bg-yellow-gradient-plain",
    "key":"8",
  },

];
